# Generated by Django 4.2.2 on 2024-07-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_category_music_playlist_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='category',
            field=models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('hiphop', 'Hip Hop'), ('jazz', 'Jazz'), ('classical', 'Classical')], max_length=50),
        ),
    ]
