# Generated by Django 4.2.2 on 2024-07-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_music_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='audio_file',
            field=models.FileField(default='music/placeholder.mp3', upload_to='music/'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='musics',
            field=models.ManyToManyField(related_name='playlists', to='music.music'),
        ),
    ]
